name: Linter
on: [push]

jobs:
  code-black:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Black and flake8
        run: pip install black==23.12.1 flake8
      - name: Run Black
        run: python -m black --config=pyproject.toml --check torch_audiomentations tests test_fixtures

      - name: Lint with flake8
        # Exit on important linting errors and warn about others.
        run: |
          python -m flake8  torch_audiomentations tests  --show-source --statistics  --select=F6,F7,F82,F52
          python -m flake8 --config .flake8 --exit-zero torch_audiomentations tests --statistics
